import { DAY, SECOND } from "$lib";
import * as auth from "$lib/server/auth";
import { db, schema, sessionCacheTag } from "$lib/server/db";
import { error, redirect } from "@sveltejs/kit";
import { and, eq } from "drizzle-orm";

export const handle = async ({ event, resolve }) => {
	if (event.url.pathname === "/api/proxy") {
		return resolve(event);
	}

	event.locals.sessionUser = null;
	event.locals.sessionId = null;

	console.log(event.request.method, event.url.pathname, new URL(event.request.url).pathname);

	// if there is an unexpired access token cookie, verify it
	try {
		const accessTokenCookie = event.cookies.get(auth.ACCESS_TOKEN_COOKIE_NAME);
		// console.log("using access token");
		if (accessTokenCookie == null) throw new Error("pass to catch");
		const { payload } = await auth.verifyAccessToken(accessTokenCookie);
		event.locals.sessionId = payload.sessionId;

		// const exp = payload.exp! * 1000;
		// const now = Date.now();
		// console.log(now, exp - now);
	} catch {
		// console.log("access token verification failed");

		// if the access token verification fails, then try the refresh token
		const refreshTokenCookie = event.cookies.get(auth.REFRESH_TOKEN_COOKIE_NAME);

		if (refreshTokenCookie != null) {
			// console.log("using refresh token");
			// if its not expired yet, verify it:
			try {
				// if the refresh token is still valid, generate the new tokens
				const { payload } = await auth.verifyRefreshToken(refreshTokenCookie);
				// const exp = payload.exp! * 1000;
				// const now = Date.now();
				// console.log(now, exp - now);
				// console.log("refresh token verified");
				// todo: should the payload be regenerated by connecting to db?
				await auth.setTokenCookies(event, payload.sessionId);
				event.locals.sessionId = payload.sessionId;
				// todo: switch to jws, and update here.
				// also, update the account details if it has not been updated in the last 24h.
				// update the session last_used_at as well (create that field first)
			} catch {
				// console.log("refresh token verification failed");
				auth.deleteTokenCookies(event);
				event.locals.sessionId = null;
			}
		}
	}

	// if the user have been authenticated:
	if (event.locals.sessionId != null) {
		// console.log("auth successful");
		if (event.route.id == "/login") {
			// todo: refactor for all "non-protected" routes
			redirect(307, "/");
		}

		// console.log("finding session");
		// todo: jws & no shity

		const [dbSession] = await db
			.select({
				session: {
					id: schema.sessions.id,
					accessToken: schema.sessions.accessToken,
					deviceInfo: schema.sessions.deviceInfo,
					deviceType: schema.sessions.deviceType,
					createdAt: schema.sessions.createdAt
				},
				account: {
					username: schema.accounts.username,
					semesterId: schema.accounts.semesterId,
					lastUpdatedAt: schema.accounts.lastUpdatedAt
				},
				college: {
					id: schema.colleges.id,
					name: schema.colleges.name,
					baseUrl: schema.colleges.baseUrl
				},
				settings: {
					attendancePercentMax: schema.settings.attendancePercentMax,
					attendancePercentMin: schema.settings.attendancePercentMin,
					expandAttendanceSubjects: schema.settings.expandAttendanceSubjects,
					invalidAttendanceMarker: schema.settings.invalidAttendanceMarker,
					showAttendanceBarByDefault: schema.settings.showAttendanceBarByDefault
				},
				notificationServerSettings: {
					url: schema.notificationServerSettings.url,
					apiKey: schema.notificationServerSettings.apiKey,
					authToken: schema.notificationServerSettings.authToken,
					vapidKey: schema.notificationServerSettings.vapidKey,
					etlabAccessToken: schema.notificationServerSettings.etlabAccessToken
				}
			})
			.from(schema.sessions)
			.innerJoin(
				schema.accounts,
				and(
					eq(schema.accounts.username, schema.sessions.accountUsername),
					eq(schema.accounts.collegeId, schema.sessions.collegeId)
				)
			)
			.innerJoin(schema.colleges, eq(schema.colleges.id, schema.accounts.collegeId))
			.leftJoin(
				schema.settings,
				and(
					eq(schema.settings.accountUsername, schema.accounts.username),
					eq(schema.settings.collegeId, schema.accounts.collegeId)
				)
			)
			.leftJoin(
				schema.notificationServerSettings,
				and(
					eq(schema.notificationServerSettings.accountUsername, schema.accounts.username),
					eq(schema.notificationServerSettings.collegeId, schema.accounts.collegeId)
				)
			)
			.where(eq(schema.sessions.id, event.locals.sessionId))
			.limit(1)
			.$withCache({
				tag: sessionCacheTag(event.locals.sessionId),
				config: { ex: (14 * DAY) / SECOND }
			});

		if (dbSession == null) {
			auth.deleteTokenCookies(event);
			event.locals.sessionId = null;
			redirect(307, "/login");
		}
		// await auth.setTokenCookies(event, dbSession.id);
		event.locals.sessionUser = {
			session: dbSession.session,
			account: dbSession.account,
			college: dbSession.college,
			settings: dbSession.settings,
			notificationServerSettings: dbSession.notificationServerSettings
		};
		return resolve(event);
	} else {
		if (event.url.pathname.startsWith("/api")) {
			return resolve(event);
		}
		// console.log("unauthorized");
		if (event.route.id == "/login") {
			// console.log("at login");
			return resolve(event);
		}
		redirect(307, "/login");
	}

	error(500, "Impossible!");
};
